apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkout
  template:
    metadata:
      labels:
        app: checkout
    spec:
      containers:
        - name: checkout
          image: polinux/stress
          command: ["stress"]
          args: ["--vm", "1", "--vm-bytes", "1536M", "--vm-hang", "1"]
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 512Mi
